### ISSUE TITLE
/stop causes exception error

### ISSUE THREAD

**Issue by mrfloris** [WeNeedCoffee/FoundDiamonds#3]
Hi there, I have to be honest and say I haven't had time to update yet to the spigot upload. But just in case this is something that affects both versions, I thought I wouldn't ignore it and share this exception error regardless. 

```
[13:46:53] [Server thread/INFO]: [FoundDiamonds] Disabling FoundDiamonds v3.6.6
[13:46:53] [Server thread/INFO]: [FoundDiamonds] Saving all data...
[13:46:53] [Server thread/ERROR]: Error occurred while disabling FoundDiamonds v3.6.6 (Is it up to date?)
java.lang.NullPointerException: null
        at co.proxa.founddiamonds.file.FileHandler.writeBlocksToFile(FileHandler.java:99) ~[?:?]
        at co.proxa.founddiamonds.file.FileHandler.saveFlatFileData(FileHandler.java:239) ~[?:?]
        at co.proxa.founddiamonds.FoundDiamonds.onDisable(FoundDiamonds.java:101) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.disablePlugins(CraftServer.java:427) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:717) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:644) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:889) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-c3a49df-2f18108]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[13:46:53] [Server thread/INFO]: Saving players
```

Each time I close the server, I notice this. 

[config.yml.zip](https://github.com/WeNeedCoffee/FoundDiamonds/files/4890405/config.yml.zip)

**Comment by Dalethium** [comment]
https://github.com/WeNeedCoffee/FoundDiamonds/releases/tag/4.0.4-SNAPSHOT

Please give this a try and let me know
